# Generated by Django 4.1.7 on 2023-03-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50, null=True)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('empresa', models.CharField(default='', max_length=50, null=True)),
                ('Estatus', models.CharField(default='Activo', max_length=50)),
                ('Solicitante', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(default='', max_length=50)),
                ('Estatus', models.CharField(default='Entro', max_length=50)),
                ('placa', models.CharField(default='', max_length=50)),
                ('fecha', models.CharField(default='', max_length=50)),
                ('empresa', models.CharField(default='', max_length=50, null=True)),
                ('foto_1', models.ImageField(null=True, upload_to='uploads/')),
                ('foto_2', models.ImageField(null=True, upload_to='uploads/')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitas.persona')),
            ],
        ),
    ]
