# Generated by Django 4.1.7 on 2023-03-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visita',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
