# Generated by Django 4.1.7 on 2023-03-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_alter_persona_id_alter_visita_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Estatus',
            field=models.CharField(choices=[('ACTIVO', 'activo'), ('BETADO', 'Betado')], default='ACTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.DateField(default='', max_length=50),
        ),
    ]
