# Generated by Django 4.1.7 on 2023-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0004_alter_visita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='carro',
            field=models.BooleanField(default=False),
        ),
    ]
