# Generated by Django 4.1.7 on 2023-03-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0005_visita_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitasProgramadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carro', models.BooleanField(default=False)),
                ('motivo', models.CharField(default='', max_length=50)),
                ('Estatus', models.CharField(default='Entro', max_length=50)),
                ('placa', models.CharField(default='', max_length=50)),
                ('fecha', models.CharField(default='', max_length=50)),
                ('empresa', models.CharField(default='', max_length=50, null=True)),
                ('foto_1', models.ImageField(null=True, upload_to='uploads/')),
                ('foto_2', models.ImageField(null=True, upload_to='uploads/')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitas.persona')),
            ],
        ),
    ]
