# Generated by Django 4.1.7 on 2023-03-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0006_visitasprogramadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='persona_visita',
            field=models.CharField(default='', max_length=50),
        ),
    ]
