# Generated by Django 4.1.7 on 2023-03-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0008_visita_persona_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='persona_actual',
            field=models.IntegerField(),
        ),
    ]
