# Generated by Django 4.1.7 on 2023-03-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0012_alter_visita_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.DateField(),
        ),
    ]
