# Generated by Django 4.1.7 on 2023-03-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0013_alter_visita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fecha',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitasprogramadas',
            name='placa',
            field=models.DateField(),
        ),
    ]
