# Generated by Django 4.1.7 on 2023-03-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0015_alter_visitasprogramadas_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitasprogramadas',
            name='persona_visita',
            field=models.CharField(default='', max_length=50),
        ),
    ]
