# Generated by Django 4.1.7 on 2023-03-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0017_persona_foto_1_alter_visitasprogramadas_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
