# Generated by Django 4.1.7 on 2023-03-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0018_alter_visita_foto_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
